version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fast_backend
    volumes:
      - ./backend/sql_app.db:/app/sql_app.db
      # If you created a .env file on VPS, ensure docker reads it:
      # - ./backend/.env:/app/.env 
    restart: always

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"  # <--- Added HTTPS Port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # <--- Added SSL Cert Access
    depends_on:
      - frontend
      - backend
    restart: always
