"""Pydantic schemas for EU market strategy endpoints."""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator

from app.core.sanitization import has_prompt_injection_markers, sanitize_user_text


class CollectRegulationsRequest(BaseModel):
    """Request payload for crawling regulation sources."""

    query: str = Field(
        default="EU and German regulations for startup market entry",
        min_length=5,
        max_length=500,
        description="Search query used for regulation discovery.",
    )
    max_results: int = Field(default=8, ge=1, le=20)

    @field_validator("query")
    @classmethod
    def validate_query(cls, value: str) -> str:
        cleaned = sanitize_user_text(value)
        if len(cleaned) < 5:
            raise ValueError("Query is too short.")
        if has_prompt_injection_markers(cleaned):
            raise ValueError("Query contains unsupported instructions.")
        return cleaned


class CollectRegulationsResponse(BaseModel):
    """Result of regulation crawl and ingestion."""

    discovered_pdf_urls: int
    downloaded_pdfs: int
    ingested_chunks: int
    tavily_documents_ingested: int = 0
    local_documents_ingested: int = 0
    sources: list[str]


class StrategyRequest(BaseModel):
    """Business idea payload sent by frontend."""

    business_idea: str = Field(..., min_length=10, max_length=500)
    market_focus: str = Field(default="Germany and EU", min_length=2, max_length=120)

    @field_validator("business_idea", "market_focus")
    @classmethod
    def sanitize_text_fields(cls, value: str) -> str:
        cleaned = sanitize_user_text(value)
        if not cleaned:
            raise ValueError("Value cannot be empty.")
        if has_prompt_injection_markers(cleaned):
            raise ValueError("Input contains unsupported instructions.")
        return cleaned


class StrategyPayload(BaseModel):
    """Structured strategy response generated by the workflow."""

    key_regulations: list[str]
    business_opportunities: list[str]
    marketing_strategy: list[str]
    compliance_checklist: list[str]
    implementation_roadmap: list[str]


class StrategyResponse(BaseModel):
    """Final API output for strategy generation."""

    query: str
    rewritten_query: str
    strategy: StrategyPayload
    retrieved_sources: list[str]
    pdf_report: str
